### ISSUE TITLE
Weapons can shoot through walls

### ISSUE THREAD

**Issue by maikmerten** [xenon-tech/Quirky#106]
When walking directly up to a wall the projectiles apparently spawn within the wall and travel into adjacent rooms.

![g9skq](https://cloud.githubusercontent.com/assets/2611432/5864868/99a968fa-a285-11e4-9690-0f3bba13f765.jpg)

edit: In the picture above there's a glass window between the player's location and the room below. Works also when shooting "solid" walls, though.

**Comment by hogsy** [comment]
Nice, thanks again. I'll look into this when I sort out the issue regarding aim vectors and I'll see what I can do :)

**Comment by hogsy** [comment]
A potential solution I can think of that would be effective, would be to run a trace a short bit in-front of a physics object to determine where to stop before it hits something and when applying the velocity, it would then additionally limit the final position to that end trace point.

**Comment by hogsy** [comment]
This is sort of fixed but needs refining, currently being backed up against a wall means one can't fire because the trace is too large (unintentionally). Instead do a trace without giving it any scale, and _then_ an additional trace with sizing.

**Comment by hogsy** [comment]
@maikmerten what's the status on this, would you say it's fixed now or do I still need to do more work on it?

**Comment by maikmerten** [comment]
One can still shoot through the glass window in e1m2a (see screenshot above), so no news regarding that

**Comment by hogsy** [comment]
Will look at this again soon then! Thanks

On 17 February 2016 at 17:35, maikmerten <notifications@github.com> wrote:

> One can still shoot through the glass window in e1m2a (see screenshot
> above), so no news regarding that
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OldTimes-Software/KatanaEngine/issues/106#issuecomment-185317465>
> .
>



-- 
*Mark Elsworth Sowden*
Lead Programmer @ OldTimes Software <http://oldtimes-software.com/>
